version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: djibril
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-startup
